name: "이슈 생성"
description: "Repo에 이슈를 생성하고 Jira와 자동 연결됩니다. 라벨을 하나 선택해주세요"
labels: [chore]
title: "이슈 이름을 간단하게 적어주세요"
body:
  - type: input
    id: parent_task
    attributes:
      label: "상위 작업 티켓"
      description: "상위 작업의 Ticket Number를 기입해주세요"
      placeholder: "NVS-62"
      value: "NVS-62"
    validations:
      required: true

  - type: dropdown
    id: jira_issuetype
    attributes:
      label: "이슈 유형"
      description: "Jira에 생성될 이슈의 유형을 선택하세요"
      options:
        - Story
        - Task
        - Subtask
      default: 1
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: "이슈 설명"
      description: "생성할 이슈에 대해 설명을 넣어주세요"
    validations:
      required: true
