name: Extract Jira Key on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  extract-key-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract issue number from branch name
        id: extract_issue
        if: contains(github.head_ref, '#')
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          ISSUE_NUMBER="${BRANCH_NAME##*#}"
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT

      - name: Get Issue Title
        id: issue
        if: steps.extract_issue.outputs.issue_number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_TITLE=$(gh issue view ${{ steps.extract_issue.outputs.issue_number }} --json title -q .title)
          echo "issue_title=${ISSUE_TITLE}" >> $GITHUB_OUTPUT

      - name: Extract Jira Key from issue title
        id: extract_key
        if: steps.extract_issue.outputs.issue_number
        run: |
          ISSUE_TITLE="${{ steps.issue.outputs.issue_title }}"
          JIRA_KEY=$(echo "${ISSUE_TITLE}" | grep -o -E '[A-Z]+-[0-9]+')
          echo "jira_key=${JIRA_KEY}" >> $GITHUB_OUTPUT

      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Change status to "In Progress"
        uses: atlassian/gajira-transition@v3
        if: steps.extract_key.outputs.jira_key
        with:
          issue: ${{ steps.extract_key.outputs.jira_key }}
          transition: "완료"
